//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thimau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinhvien
    {
        public string Masv { get; set; }
        public string Hosv { get; set; }
        public string Tensv { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string Anhsv { get; set; }
        public string Diachi { get; set; }
        public string Malop { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
